// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxb1LaJ4YXgkzIJUsZdouJEnUanoRx_fg',
    appId: '1:565485235740:web:cd45d1a6f8e565fc49b9d9',
    messagingSenderId: '565485235740',
    projectId: 'jabla-insect',
    authDomain: 'jabla-insect.firebaseapp.com',
    databaseURL: 'https://jabla-insect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jabla-insect.firebasestorage.app',
    measurementId: 'G-XTJRCGH5K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5IO25z018iL3Vlo7yRxy75HvfYPULAE',
    appId: '1:565485235740:android:b01e8114f5bf2d1e49b9d9',
    messagingSenderId: '565485235740',
    projectId: 'jabla-insect',
    databaseURL: 'https://jabla-insect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jabla-insect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXZVjjB4vz3LlFA7SOe2rnCLBP7J3o9w',
    appId: '1:565485235740:ios:ed9bcf0ec5265c5849b9d9',
    messagingSenderId: '565485235740',
    projectId: 'jabla-insect',
    databaseURL: 'https://jabla-insect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jabla-insect.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXZVjjB4vz3LlFA7SOe2rnCLBP7J3o9w',
    appId: '1:565485235740:ios:ed9bcf0ec5265c5849b9d9',
    messagingSenderId: '565485235740',
    projectId: 'jabla-insect',
    databaseURL: 'https://jabla-insect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jabla-insect.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxb1LaJ4YXgkzIJUsZdouJEnUanoRx_fg',
    appId: '1:565485235740:web:6aa21d97bb568f0c49b9d9',
    messagingSenderId: '565485235740',
    projectId: 'jabla-insect',
    authDomain: 'jabla-insect.firebaseapp.com',
    databaseURL: 'https://jabla-insect-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jabla-insect.firebasestorage.app',
    measurementId: 'G-5DT8GZECVT',
  );

}