import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // <- generated by FlutterFire CLI

import 'package:test/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Sign in anonymously to allow database access
  try {
    await FirebaseAuth.instance.signInAnonymously();
    debugPrint("Signed in anonymously");
  } catch (e) {
    debugPrint("Failed to sign in anonymously: $e");
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Insect Identifier',
      debugShowCheckedModeBanner: false,
      home: const SplashScreen(),
    );
  }
}
